selenium:
  headless: true
  timeoutSec: 60
  driver:
    path: /Users/antonzhuikov/IdeaProjects/ExchangeRatesJava/common/SeleniumEngineStarter/src/main/resources/drivers/chromedriver_mac
    type: webdriver.chrome.driver
forex:
  user:
    login: wordscreators@gmail.com
    password: WOrdscreators
spring:
  kafka:
    topics:
      parsed-eur-usd:
        consumer: false
        producer: false
      action-eur-usd:
        consumer: false
        producer: false
      parsed-cup-eur-usd:
        consumer: false
        producer: true
    bootstrap-servers: ${kafka_bootstrap_servers:kafka:9092}
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${kafka_username:'admin'} password=${kafka_password:'admin-secret'};
        mechanism: PLAIN
      security:
        protocol: SASL_PLAINTEXT
    consumer:
      auto-offset-reset: earliest
      group-id: forexParser
      max-poll-records: 1
      fetch-max-wait: 36000
      enable-auto-commit: false
      client-id: forexParser
    producer:
      client-id: forexProducer
      retries: 2
    jaas:
      enabled: true
    listener:
      poll-timeout: 1800000
      concurrency: 1
      ack-mode: manual_immediate
