spring:
  kafka:
    topics:
      parsed-eur-usd:
        consumer: true
        producer: false
      parsed-cup-eur-usd:
        consumer: true
        producer: false
      action-eur-usd:
        consumer: true
        producer: false
    bootstrap-servers: ${kafka_bootstrap_servers:kafka-service:9092}
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${kafka_username:'admin'} password=${kafka_password:'admin-secret'};
        mechanism: PLAIN
      security:
        protocol: SASL_PLAINTEXT
    consumer:
      auto-offset-reset: earliest
      group-id: storedParsedRatesGroup
      max-poll-records: 1
      fetch-max-wait: 36000
      enable-auto-commit: false
      client-id: strategyEmaRsiStoch
    producer:
      client-id: strategyEmaRsiStoch
      retries: 2
    jaas:
      enabled: true
    listener:
      poll-timeout: 1800000
      concurrency: 1
      ack-mode: manual_immediate
  datasource:
    url: jdbc:mysql://mysql/todo_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
server:
  port: 8081
