selenium:
  headless: true
  timeoutSec: 60
  driver:
    path: /Users/antonzhuikov/IdeaProjects/ExchangeRatesJava/src/main/resources/selenium/drivers/chromedriver
    type: webdriver.chrome.driver
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
server:
  port: 8081
forex:
  user:
    login: wordscreators@gmail.com
    password: WOrdscreators
logging:
  level:
    - root: debug