kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:2.12-2.5.0
          ports:
            - containerPort: 9092
          volumeMounts:
            - mountPath: /etc/jaas
              name: jaas
          env:
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: 'true'
#            - name: KAFKA_ADVERTISED_PORT
#              value: "30718"
#            - name: KAFKA_ADVERTISED_HOST_NAME
#              value: kafka

            - name: KAFKA_ADVERTISED_LISTENERS
              value: INSIDE://kafka-service:9093,OUTSIDE://kafka-service:9092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INSIDE:PLAINTEXT,OUTSIDE:SASL_PLAINTEXT
            - name: KAFKA_LISTENERS
              value: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-service:2181
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INSIDE
            - name: KAFKA_OPTS
              value: '-Djava.security.auth.login.config=/etc/jaas/jaas.conf'
            - name: KAFKA_SASL_ENABLED_MECHANISMS
              value: PLAIN
            - name: KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL
              value: PLAIN
      volumes:
        - name: jaas
          configMap:
            name: jaas-config
