kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka
  namespace: default
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: zookeeper
          image: wurstmeister/zookeeper
          ports:
            - name: http
              containerPort: 2181
              protocol: TCP
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
              protocol: TCP
              name: http-outside
            - containerPort: 9093
              protocol: TCP
              name: http-inside
          volumeMounts:
            - mountPath: /etc/kafka
              name: kafka-server-jaas-config
              readOnly: true
          env:
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: 'true'
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INSIDE://kafka:9093,OUTSIDE://localhost:9092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INSIDE:PLAINTEXT,OUTSIDE:SASL_PLAINTEXT
            - name: KAFKA_LISTENERS
              value: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INSIDE
            - name: KAFKA_OPTS
              value: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
            - name: KAFKA_SASL_ENABLED_MECHANISMS
              value: PLAIN
            - name: KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL
              value: PLAIN
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: kafka.username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: kafka.password
            - name: USER_ADMIN
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: kafka.user.admin
      volumes:
        - name: kafka-server-jaas-config
          configMap:
            name: kafka-server-jaas
            defaultMode: 420
