spring:
  kafka:
    topics:
      parsed-eur-usd:
        consumer: false
        producer: false
      parsed-cup-eur-usd:
        consumer: true
        producer: false
      action-eur-usd:
        consumer: false
        producer: true
    bootstrap-servers: ${kafka_bootstrap_servers:host.minikube.internal:9094}
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${kafka_username:'admin'} password=${kafka_password:'admin-secret'};
        mechanism: PLAIN
      security:
        protocol: SASL_PLAINTEXT
    consumer:
      auto-offset-reset: earliest
      group-id: strategyEmaRsiStoch
      max-poll-records: 1
      fetch-max-wait: 36000
      enable-auto-commit: false
      client-id: strategyEmaRsiStoch
    producer:
      client-id: strategyEmaRsiStoch
      retries: 2
    jaas:
      enabled: true
    listener:
      poll-timeout: 1800000
      concurrency: 1
      ack-mode: manual_immediate
